language: node_js
sudo: false
node_js:
  - "6.3"
  - "6.0"
script:
  - npm install node-deb@0.1.16
  - npm test
  - node-deb -n ob-relay.deb -- app.js package.json lib/ node_modules/
before_deploy:
  - export RELEASE_PKG_FILE=$(ls *.deb)
deploy:
  provider: releases
  api_key:
    secure: A6q8pmDGly6cjhEGTe8+u0evIGGg9RWWw8F2DdQ5U3xaeZ5XvxIc7H0PllHSFPJPzUpTVVJeP/0zWkI860BmSz+1ScFI9F73U/a78piR6QNAdYpQf5tDLwqdkUfFlXSuqFHvWp4flQGnP7KPx0jGFAXKkp8ruygWmGmDSPqPC+52rjp2hXq5EVYYStUB0iFGew6Z8P4QJdZuj4VQypU+PoYpsdinaVdpLHdWdfAree6oWEoupNah2dq7bripRF77qqvm3jQv7fLOY/5/v+rGu18ri4NfIFqRYARztVlQfg972eW3bGlrCz0gxmlz0mBz1zN/3HustNJgOcHY2raj3cxHc6mxBI3rSTtpmI+j7p15LeIToARPmHZtHN8kAulHVl+KqAvsB1YcqOHLjBoXhGdc6s1LXwFWy5jdAp/7v28tXRkIXaL2ywolJfjpvqlwiMOe3dLkTPqMOujLSDgWZzxhBr7zoTLx7udYQt7UCPH6WuGOspVy7MMrXcdR4Kx0damTRCJrfTkcSxlgz/rn9XaPMOzRLjRGTcss/4greCMj8B2Xtw8eanUtpXKUVuzbUPENM4VW++E4rDOcA0oadSC2gclyeGp+/QAXFW3OKMBaiTqTCz1mi8sWFfHCVx6spDVXbhtHHV+pkeaSTl1Z7z3f2Uo8ad7Xu8U3jtxGN9I=
  skip_cleanup: true
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  on:
    tags: true
env:
  global:
    secure: WvTaprkryt7qwCr4LiYVdU9OX6R8Oxba2dJ+aJdNgtKux3pj1RMyE72EA5S5IP/Qq5rP/e6AMvzfeCDLy+Hqf7eDMgRb+Vsi4LJAneGnoMytv4sGue39WfEJk6mdPNzp1li23hsUqyKQNdMouxv1spG9Xbe4P+fPRECeXIuoa/RcJq+SFYfv6ioxJUahTk3r0+4yWGkB2Ivv1yZysx1Bb9tLw+aly2pscHWhQcWcXU6t+2kpVyymWvJvPKucyxg0h40ZBpYMd/BYUxP8r2sRA1o1l0WfQOUhiUL8BF/xqf4K4CZsSLr61LZqH0tsignNwBPXnOGPUWdeRs+xp9a+0ngvG8RUOpsKLxlQjBJ6nsh1n6ArSMHT53mdWArvp0gode+yLJodj6pi7nstPz4l32m9NZCeqM/nLBOaq8X7mPW13Wn1UeVi2VFlnvRX/Tx5qmpwwJyh969rUkiod9deJt89heOp/LzYK+58ctaIgdc577KGRcpnq8lh7iN8Z0HLmIUWPACYkfimmLI3pMNmhihS/tByfa7SC67lofrNHQVikFfYn/xAydCB8YbF1dTw25EUEvCgJS37Mw9GjRohXYOV/hwT0DQzgfsAL6o+bHak57UbrI9JVGMYZNclKJlOT8ORhDjCJmJ9lVNVuj2XhhqGrgXhKKnCGbxuwiKOJBo=
